# Generated by Django 3.2.19 on 2023-06-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_pdfs_extra_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfs',
            name='extra_field',
        ),
    ]
