# Generated by Django 3.2.19 on 2023-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_pdfs_extra_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfs',
            name='pdf',
        ),
        migrations.AddField(
            model_name='pdfs',
            name='name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfs',
            name='pdf_file',
            field=models.FileField(default=None, max_length=256, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
